micronaut:
  application:
    name: nestpicker
datasources:
  default:
    url: jdbc:postgresql:${database.host}
    driverClassName: org.postgresql.Driver
    username: ${database.username}
    password: ${database.password}
